Allow dynamic shapes inference in GPU
intel/onnxruntime pull request #290
Opened 2023-04-18 10:02 UTC by sspintel

### Description

- Allow dynamic shapes inference in GPU when enable_dynamic_shapes=True is set (Lines of interest: [Link 1](https://github.com/intel/onnxruntime/pull/290/files#diff-84b5dc31f64204b79173c207589103341ae50d58779a3e03092a6eb9b8e5cb7fL266) [Link 2](https://github.com/intel/onnxruntime/pull/290/files#diff-84b5dc31f64204b79173c207589103341ae50d58779a3e03092a6eb9b8e5cb7fR80) [Link 3](https://github.com/intel/onnxruntime/pull/290/files#diff-10ceae516462e95d43795fa0eb5ac08caa78e2e0ed0ed7491347ee840f8ca765R165)
- Add Synchronous inference API Infer(); Useful for debugging purposes (Files of interest: ov_interface.*)
- Added formatting changes in the files involved (Rest of the lines)

2023-04-18 12:14 UTC, MaajidKhan requested changes

2023-04-19 04:44 UTC, sspintel commented on onnxruntime/core/providers/openvino/ov_interface.cc
> +    void OVInferRequest::Infer() {
Yes it's not being used now, but debugging into OpenVINO code during async inference calls is difficult as we have to track down which thread the inference is actually running on. Instead, when debugging I just replace StartAsync with Infer and remove Wait.

2023-04-19 05:52 UTC, sspintel commented on onnxruntime/core/providers/openvino/backend_manager.cc
> +    LOGS_DEFAULT(INFO) << "[OpenVINO-EP] Model has concrerte input dims. Initializing backend for graph " << subgraph_context_.subgraph_name;
Fixed typo

2023-04-19 05:55 UTC, sspintel commented on onnxruntime/core/providers/openvino/backend_manager.cc
> +          concrete_backend_ = BackendFactory::MakeBackend(*model_proto_,
I think we can keep these variables as-is Maajid. It's a bit confusing if we think about tensor shapes (static vs dynamic) but here concrete and dynamic seem to refer to whether backends get created once during initialization (for static inputs or for backends supporting dynamic shapes) or for every unique shape for backends that don't.

2023-04-19 06:50 UTC, merged

2023-04-19 06:50 UTC, MaajidKhan commented
Thanks SP. PR is now merged.