Move the scope of model proto to local
intel/onnxruntime pull request #425
Opened 2024-08-26 12:30 UTC by preetha-intel

### Description
Move the scope of model proto and clean it up from memory before OV read_model

2024-08-26 12:33 UTC, sfatimar commented on onnxruntime/core/providers/openvino/backends/basic_backend.cc
> +        const std::string model = model_proto->SerializeAsString();
Model Proto changes look ok but should we keep string as constant as we want to delete it later ?

2024-08-26 14:56 UTC, javier-intel requested changes

2024-08-26 14:56 UTC, javier-intel commented on onnxruntime/core/providers/openvino/backends/basic_backend.cc
> +          auto model_proto_ptr = model_proto.release();
To avoid code bloat please leave this combined in one line

2024-08-26 14:56 UTC, javier-intel commented on onnxruntime/core/providers/openvino/backend_manager.cc
> -  model_proto_ = GetModelProtoFromFusedNode(fused_node, subgraph, logger);
Please leave this line here and manage the result as needed. Replicating the call results in spaghetti code as it isn't clear why there are multiple calls. Here's the original code for reference https://github.com/intel-sandbox/jemartin-onnxruntime/commit/792523185d156550165eab34c92184b25bf09267

2024-08-27 06:22 UTC, preetha-intel commented
Another PR with fix for dynamic backend is raised and merged. 
[https://github.com/intel/onnxruntime/pull/427](https://github.com/intel/onnxruntime/pull/427) 
Closing as its duplicate.

2024-08-27 06:22 UTC, closed without merging