update: Update MSFT Contrib Ops in OVEP
intel/onnxruntime pull request #521
Opened 2024-12-11 15:13 UTC by ankitm3k

### Description
This PR Updates the latest OV supported Contrib Ops in OVEP

2024-12-12 08:34 UTC, MayureshV1 commented
@ankitm3k, Can you please test a few models with these custom ops and ensure only the backends/ devices that are functional are called out as supported.

2024-12-18 06:29 UTC, saurabhkale17 requested changes

2024-12-18 06:29 UTC, saurabhkale17 commented on onnxruntime/core/providers/openvino/ov_versions/data_ops.cc
> +    {"Attention", V_2024_5, {"CPU","GPU","NPU"}},
@ankitm3k 
Currently, we do not have specific operator mapping for the NPU. Instead, we rely on CPU operator support. If model compilation fails on the NPU, it automatically falls back to the CPU. As a result, graph partitioning is determined based on the operator support available on the CPU. So NPU can be removed from all the ops.

You can see this mapping in the constructor of get capability.
[https://github.com/intel/onnxruntime/blob/0981bbf4ca4af4d7216299f15de784f19ce6123a/onnxruntime/core/providers/openvino/ov_versions/capability.cc#L34]

2025-01-24 12:48 UTC, n1harika commented
Modified data_ops.cc to remove unsupported ops, namely:

SkipSimplifiedLayerNormalization
SimplifiedLayerNormalization
QuickGelu
FusedMatMul

This PR adds support for: 

Attention
BiasGelu
EmbedLayerNormalization
FusedConv
FusedGemm
MatMulNBits
SkipLayerNormalization

2025-01-24 13:59 UTC, n1harika commented on onnxruntime/core/providers/openvino/ov_versions/data_ops.cc
> +    {"Attention", V_2024_5, {"CPU","GPU","NPU"}},
Noted, I have removed NPU mapping for all ops.

2025-01-24 14:14 UTC, ankitm3k commented on onnxruntime/core/providers/openvino/ov_versions/data_ops.cc
> +    {"Attention", V_2024_5, {"CPU","GPU","NPU"}},
Resolving as its fixed now.

2025-02-06 09:05 UTC, n1harika commented
Spreadsheet used in testing the various operators: https://intel-my.sharepoint.com/:x:/p/ankit_maheshkar/EeMj4cZ-2XNEpoWznBgtKc8B6f7oKR9uZjlWNKUH0VYqdg?e=dihHPM

JIRA: https://jira.devtools.intel.com/browse/CVS-160502

2025-02-10 06:06 UTC, sfatimar commented
@ankitm3k  PR is unblocked Please rebase, review and ready to merge

2025-02-10 16:06 UTC, ankitm3k commented
> @ankitm3k PR is unblocked Please rebase, review and ready to merge

LGTM. Reviewed it

2025-02-11 08:01 UTC, sfatimar commented
LGTM

2025-02-11 08:02 UTC, merged

2025-04-03 14:03 UTC, sfatimar reviewed
Approved